// This file is auto-generated by @hey-api/openapi-ts

export type Planet = {
    id: string;
    name: string;
};

export type NewPlanet = {
    name: string;
};

export type UpdatedPlanet = {
    id: string;
};

export type PlanetListData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/planets';
};

export type PlanetListResponses = {
    /**
     * A list of planets
     */
    200: Array<Planet>;
};

export type PlanetListResponse = PlanetListResponses[keyof PlanetListResponses];

export type PlanetCreateData = {
    body: NewPlanet;
    path?: never;
    query?: never;
    url: '/planets';
};

export type PlanetCreateResponses = {
    /**
     * A updated planet
     */
    200: UpdatedPlanet;
    /**
     * A created planet
     */
    201: Planet;
};

export type PlanetCreateResponse = PlanetCreateResponses[keyof PlanetCreateResponses];

export type GetPlanetData = {
    body?: never;
    path: {
        planetId: string;
    };
    query?: never;
    url: '/planets/{planetId}';
};

export type GetPlanetErrors = {
    /**
     * Not found
     */
    404: number;
};

export type GetPlanetError = GetPlanetErrors[keyof GetPlanetErrors];

export type GetPlanetResponses = {
    /**
     * A planet
     */
    200: Planet;
};

export type GetPlanetResponse = GetPlanetResponses[keyof GetPlanetResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};