// This file is auto-generated by @hey-api/openapi-ts

export type Planet = {
    id: string;
    name: string;
};

export type NewPlanet = {
    name: string;
};

export type ListPlanetsData = {
    body?: never;
    path?: never;
    query?: {
        limit?: number;
        offset?: number;
    };
    url: '/planets';
};

export type ListPlanetsResponses = {
    /**
     * A list of planets
     */
    200: Array<Planet>;
};

export type ListPlanetsResponse = ListPlanetsResponses[keyof ListPlanetsResponses];

export type CreatePlanetData = {
    body: NewPlanet;
    path?: never;
    query?: never;
    url: '/planets';
};

export type CreatePlanetResponses = {
    /**
     * A created planet
     */
    201: Planet;
};

export type CreatePlanetResponse = CreatePlanetResponses[keyof CreatePlanetResponses];

export type GetPlanetData = {
    body?: never;
    path: {
        planetId: string;
    };
    query?: never;
    url: '/planets/{planetId}';
};

export type GetPlanetErrors = {
    /**
     * Not found
     */
    404: number;
};

export type GetPlanetError = GetPlanetErrors[keyof GetPlanetErrors];

export type GetPlanetResponses = {
    /**
     * A planet
     */
    200: Planet;
};

export type GetPlanetResponse = GetPlanetResponses[keyof GetPlanetResponses];

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};